server:
#北京气象灾害/工具 8081
#雄安新区8981
 port: 8181
 servlet:
  context-path: /knowledge
 tomcat:
  uri-encoding: utf-8

spring:
 datasource:
#  url: jdbc:xugu://192.168.150.81:5138/HKKS
#  username: SYSDBA
#  password: SYSDBA
#雄安
#  url: jdbc:mysql://10.49.35.11:17307/hkks?useUnicode=true&characterEncoding=UTF-8
#  username: root
#  password: 123456
#  url: jdbc:mysql://172.18.130.105:3306/hkks?useUnicode=true&characterEncoding=UTF-8
  url: jdbc:mysql://10.49.35.11:17307/xa_meteo?useUnicode=true&characterEncoding=UTF-8
#  url: jdbc:mysql://localhost:3306/xa_meteo?serverTimezone=UTC
  username: root
  password: 123456
#  password: 5066
  driver-class-name: com.mysql.cj.jdbc.Driver
  platform: MySql
  type: com.alibaba.druid.pool.DruidDataSource
  # 初始化大小，最小，最大
#  initialSize: 5
#  minIdle: 3
#  maxActive: 20
#  # 配置获取连接等待超时的时间
#  maxWait: 60000
#  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#  timeBetweenEvictionRunsMillis: 60000
#  # 配置一个连接在池中最小生存的时间，单位是毫秒
#  minEvictableIdleTimeMillis: 30000
#  validationQuery: select 1 from dual
#  testWhileIdle: false
#  testOnBorrow: false
#  testOnReturn: false
#  # 打开PSCache，并且指定每个连接上PSCache的大小
#  poolPreparedStatements: true
#  maxPoolPreparedStatementPerConnectionSize: 20
  druid:
    initial-size: 20
    min-idle: 3
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    test-while-idle: false
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    validation-query: select 1 from dual
    keep-alive: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#  jpa:
#      hibernate:
#        ddl-auto: update
#      database-platform: org.hibernate.dialect.Oracle10gDialect
#      show-sql: true